export const industries = [
    "Agriculture",
"Crop Farming",
"Livestock Farming",
"Forestry",
"Fisheries",
"Mining and Natural Resources",
"Oil and Gas Extraction",
"Mining of Minerals (e.g., coal, metals, minerals)",
"Forestry and Logging",
"Fishing and Aquaculture",
"Manufacturing",
"Automotive",
"Aerospace",
"Electronics",
"Pharmaceuticals",
"Chemicals",
"Food and Beverage",
"Textiles and Apparel",
"Machinery and Equipment",
"Construction and Building Materials",
"Technology and IT",
"Software Development",
"Hardware Manufacturing",
"Telecommunications",
"E-commerce",
"Information Technology Services",
"Financial Services",
"Banking",
"Insurance",
"Investment and Securities",
"Fintech",
"Healthcare and Pharmaceuticals",
"Hospitals and Healthcare Providers",
"Pharmaceuticals Manufacturing",
"Biotechnology",
"Retail and Consumer Goods",
"Retail Stores",
"Consumer Electronics",
"Fashion and Apparel",
"Fast-Moving Consumer Goods (FMCG)",
"Energy",
"Electric Power Generation",
"Renewable Energy (e.g., solar, wind)",
"Utilities",
"Transportation and Logistics",
"Airlines",
"Shipping and Freight",
"Rail Transportation",
"Logistics and Supply Chain",
"Hospitality and Tourism",
"Hotels and Lodging",
"Travel Agencies",
"Restaurants and Food Services",
"Entertainment and Media",
"Film and Television",
"Music",
"Publishing",
"Gaming",
"Advertising",
"Construction and Real Estate",
"Residential Construction",
"Commercial Real Estate",
"Real Estate Development",
"Education",
"Schools and Universities",
"Online Education and E-learning",
"Government and Public Administration",
"Public Services",
"Defense and Military",
"Environmental Services",
"Environmental Consulting",
"Waste Management and Recycling",
"Renewable Energy",
"Automotive",
"Vehicle Manufacturing",
"Automotive Parts and Accessories",
"Legal and Professional Services",
"Law Firms",
"Consulting",
"Accounting and Auditing",
"Nonprofit and Social Services",
"Charities and Foundations",
"Social Advocacy Organizations",
"Pharmaceuticals and Biotechnology",
"Drug Discovery and Development",
"Biotech Research",
"Aerospace and Defense",
"Aircraft Manufacturing",
"Defense Contractors"
]

export const blog_types =[
"Personal Blogs",
"Travel Blogs",
"Food Blogs",
"Fashion and Beauty Blogs",
"Lifestyle Blogs",
"Parenting Blogs",
"Tech and Gadgets Blogs",
"Fitness and Wellness Blogs",
"DIY and Craft Blogs",
"Finance and Money Blogs",
"Entertainment and Pop Culture Blogs",
"Business and Entrepreneurship Blogs",
"Book and Literature Blogs",
"Political and News Blogs",
"Education and Teaching Blogs",
"Gaming Blogs",
"Travel Photography Blogs",
"Environmental and Sustainability Blogs",
"Home Improvement and Decor Blogs",
"Pet and Animal Blogs"
]