
const messages = [
    "Loading... Contemplating the meaning of life.",
    "Finding the lost sock... Please wait.",
    "Loading... Making sure the pixels are in the right order.",
    "Just loading, and I'm already tired.",
    "Thinking of a funny loading message...",
    "Counting to infinity... Loading...",
    "Loading... Patience is a virtue. Virtue is a grace. Grace is a little girl who didn't wash her face.",
    "Hold on, we're recalibrating the flux capacitor.",
    "Loading... Faster than a sloth on roller skates.",
    "Currently in hibernation mode. Wake me up when it's done loading.",
    "Loading... and then some more loading.",
    "Spinning up the hamster wheel to power this loading screen.",
    "Optimizing for your impatience.",
    "Loading... Like watching paint dry, but with more anticipation.",
    "Counting binary with fingers... Hold on.",
    "Loading... Time to make a sandwich.",
    "Finding the missing piece of the puzzle... Loading...",
    "Loading... Preparing for liftoff.",
    "Brace yourself, loading is coming.",
    "Loading... Our hamster is on vacation.",
    "Loading... Slow and steady wins the race.",
    "In the meantime, enjoy this loading screen.",
    "Loading... Making the electrons work for it.",
    "Just keep loading, loading, loading...",
    "Loading... Because even the internet needs a coffee break.",
    "Finding a needle in a haystack... Loading...",
    "Loading... Practicing patience, one loading screen at a time.",
    "Please wait while we make things less slow.",
    "Loading... Just like waiting for a pot of water to boil.",
    "Loading... We're not napping, we promise.",
    "Loading... Like watching a sloth run a marathon.",
    "Loading... The snail's pace of progress.",
    "Optimizing the unoptimizable... Loading...",
    "Loading... Because good things come to those who wait.",
    "Loading... Catching up on some light reading.",
    "Loading... Preparing for a quantum leap.",
    "Loading... The wheel's still turning, but the hamster's dead.",
    "Reaching the speed of snail... Loading...",
    "Loading... Like waiting for your cat to finish its nap.",
    "Counting to 100101101... Loading...",
    "Loading... Slow and steady, like a tortoise on tranquilizers.",
    "Loading... Waiting for the paint to dry.",
    "Finding the missing link... Loading...",
    "Loading... Making technology look easy since...",
    "Loading... Because faster isn't always better.",
    "Loading... More exciting than watching grass grow.",
    "Loading... Channeling the spirit of a sloth.",
    "Loading... Making time for a snack break.",
    "Loading... Powered by pure determination.",
    "Calculating the meaning of life... Loading...",
    "Loading... The suspense is real.",
    "Loading... Waiting for the stars to align.",
    "Finding Waldo... Loading...",
    "Loading... Just pretend it's a fast-loading screen.",
    "Loading... Making sloths look like speed demons.",
    "Loading... A journey of a thousand milliseconds begins with one click.",
    "Loading... Like watching a glacier move.",
    "Counting sheep... Loading...",
    "Loading... Almost there. No, really.",
    "Loading... Somewhere, over the loading bar.",
    "Loading... Because perfection takes time.",
    "Loading... Patiently crafting the future.",
    "Loading... Just a few moments more.",
    "Loading... Slower than a snail's grandpa.",
    "Loading... We're not procrastinating, we promise.",
    "Loading... We're on island time.",
    "Loading... Faster than a sloth on tranquilizers.",
    "Loading... The slow and the curious.",
    "Finding the lost city of Atlantis... Loading...",
    "Loading... The suspense is unbearable.",
    "Loading... Because life is too short to rush.",
    "Loading... Somewhere over the rainbow, a loading bar flies.",
    "Loading... Trust us, it's worth the wait.",
    "Loading... Waiting for the stars to align perfectly.",
    "Loading... Just a little longer. Seriously.",
    "Loading... Enjoy the elevator music.",
    "Loading... As slow as a turtle in a marathon.",
    "Loading... Like watching a snail do the cha-cha.",
    "Loading... Precision takes time.",
    "Loading... Making the seconds count.",
    "Loading... Channeling inner peace while waiting.",
    "Loading... The calm before the digital storm.",
    "Loading... We're working on our magic trick.",
    "Loading... Because quality can't be rushed.",
    "Loading... A moment of zen in the digital world.",
    "Loading... Somewhere beyond the loading bar.",
    "Loading... Even rockets take time to launch.",
    "Loading... One small step for loading bars.",
    "Loading... Almost there. Seriously.",
    "Loading... Pioneering the art of patience.",
    "Loading... Because 'fast' is overrated.",
    "Loading... Like watching a turtle break the sound barrier.",
    "Loading... We promise it'll be worth the wait.",
    "Loading... A journey to the center of the loading bar.",
    "Loading... Slower than a herd of turtles stampeding through peanut butter.",
    "Loading... Because good things come to those who wait... a lot.",
    "Loading... We're not procrastinating, we're just... loading.",
    "Loading... Embracing the digital slow dance.",
    "Loading... Making each pixel count.",
    "Loading... In the world of 1s and 0s, patience is a virtue."
]

function Loader() {
    const loadingIndex = Math.ceil(Math.random() * 100)

    return <> {messages[loadingIndex]} </>
}

export default Loader